# Conda configuration file to reproduce computing environment
#
# Create the conda environment:
#
# conda env create --file environment.yaml
#
# Update the conda environment:
#
# conda env update --file environment.yaml
#
# Activate the conda environment:
#
# source activate dc
#
# Deactivate the conda environment:
#
# source deactivate dc
#
# Resources:
#
# https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand
# https://bioconda.github.io
# https://anaconda.org/jdblischak/repo

name: dc
channels:
  - jdblischak
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconductor-geoquery
  - bioconductor-rsubread
  - bioconductor-sradb
  - r-base
  - r-dplyr
  - r-stringr
  - sra-tools

